on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: check no features
        uses: actions-rs/cargo@v1
        with:
          command: check --no-default-features 
      - name: check distributed
        uses: actions-rs/cargo@v1
        with:
          command: check --no-default-features --features "distributed"
      - name: check distributed-trace
        uses: actions-rs/cargo@v1
        with:
          command: check --no-default-features --features "distributed-trace"
      - name: check check full
        uses: actions-rs/cargo@v1
        with:
          command: check --no-default-features --features "distributed distributed-trace"
      

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - name: clippy no features
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings --no-default-features
      - name: clippy distributed
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings --no-default-features --features "distributed"
      - name: clippy distributed-trace
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings --no-default-features --features "distributed-trace"
      - name: clippy full
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings --no-default-features --features "distributed distributed-trace"